In [ ]:
# NUMPY
import numpy as np

In [ ]:
# check version
np.__version__
# to upgarade it
    # go to anaconda prompt 
    # pip install numpy --upgrade

In [ ]:
# importing pandas 
import pandas as pd
pd.__version__

In [ ]:
# MATHEMATICS 
    # LINEAR ALGEBRA
        # MATRIX
    # Scalars and Vectors
    # scalars are 1x1 matrices
    # vectors one row or one column matrices basically
    
# Scalars
import numpy as np
s = 5
s

# Vectors
v = np.array([5,-2,4])
# v is a row vector by default

# Matrices
m = np.array([[5,12,6],[-3,0,14]])

# m is a 2x3 matrix

# reshape row vector to column
v.reshape(3,1)



In [1]:
# Tensors

m1 = np.array([[5,3,9],[-2,6,4]])
m2 = np.array([[7,12,6],[-4,-2,8]])

t = np.array([m1,m2])

NameError: name 'np' is not defined

In [7]:
# Adding , Subtracting matrices
import numpy as np
m1 = np.array([[5,3,9],[-2,6,4]])
m2 = np.array([[7,12,6],[-4,-2,8]])

m3 = m1 + m2
m3

array([[12, 15, 15],
       [-6,  4, 12]])

In [9]:
# Transposing Matrices
m1 = np.array([[5,3,9],[-2,6,4]])
m1

array([[ 5,  3,  9],
       [-2,  6,  4]])

In [11]:
m1.T

array([[ 5, -2],
       [ 3,  6],
       [ 9,  4]])

In [ ]:
# continue from 72